name: "Cleanup Sanity Preview"
description: "Remove PR preview deployments for Sanity GraphQL APIs"
author: "dcilke"

inputs:
  # Required inputs
  token:
    description: "Sanity auth token for cleanup"
    required: true

  # Project configuration
  path:
    description: "Path to Sanity studio"
    required: false
    default: "."
  cli_version:
    description: "Version of Sanity CLI to install"
    required: false
    default: ""
  studio_cleanup:
    description: "Run sanity studio cleanup for the environment"
    required: false
    default: "true"
  graphql_cleanup:
    description: "Run sanity graphql undeploy for the environment"
    required: false
    default: "true"
  graphql_override_tag:
    description: "Override GraphQL tag (PR deployments use branch name)"
    required: false
    default: ""
  graphql_override_dataset:
    description: "Override GraphQL dataset"
    required: false
    default: ""

  # CI/CD features
  cache_sanity_cli:
    description: "Emit cache metadata for the local Sanity CLI install"
    required: false
    default: "false"
  comment_on_pr:
    description: "Comment cleanup status on the pull request"
    required: false
    default: "true"

  # Advanced options
  github_token:
    description: "GitHub token for PR comments"
    required: false
    default: ${{ github.token }}
  environment_variables:
    description: "Environment variables in KEY=value format"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "lts/*"

    # Install action dependencies
    - name: Install action dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}/..
        npm install --production --no-save

    # Detect package manager
    - name: Detect package manager
      id: package-manager
      shell: bash
      env:
        INPUT_PATH: ${{ inputs.path }}
      run: |
        cd ${{ inputs.path }}
        node ${{ github.action_path }}/../src/cmd/set-package-manager.js

    # Setup package manager
    - name: Setup pnpm
      if: steps.package-manager.outputs.manager == 'pnpm'
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Setup Corepack
      if: steps.package-manager.outputs.manager == 'yarn'
      shell: bash
      run: |
        cd ${{ inputs.path }}
        corepack enable

    - name: Cache Sanity CLI
      if: inputs.cache_sanity_cli == 'true'
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/.sanity-cli
        key: ${{ runner.os }}-sanity-cli-${{ steps.package-manager.outputs.manager }}-${{ inputs.cli_version != '' && inputs.cli_version || 'latest' }}
        restore-keys: |
          ${{ runner.os }}-sanity-cli-${{ steps.package-manager.outputs.manager }}-

    - name: Cleanup deployment
      id: cleanup
      shell: bash
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_PATH: ${{ inputs.path }}
        INPUT_CLI_VERSION: ${{ inputs.cli_version }}
        INPUT_STUDIO_CLEANUP: ${{ inputs.studio_cleanup }}
        INPUT_GRAPHQL_CLEANUP: ${{ inputs.graphql_cleanup }}
        INPUT_GRAPHQL_OVERRIDE_TAG: ${{ inputs.graphql_override_tag }}
        INPUT_GRAPHQL_OVERRIDE_DATASET: ${{ inputs.graphql_override_dataset }}
        INPUT_CACHE_SANITY_CLI: ${{ inputs.cache_sanity_cli }}
        INPUT_COMMENT_ON_PR: ${{ inputs.comment_on_pr }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_ENVIRONMENT_VARIABLES: ${{ inputs.environment_variables }}
      run: |
        cd ${{ inputs.path }}
        node ${{ github.action_path }}/../src/cmd/cleanup.js
